# Timeout for complete build. Default is 10m.
timeout: 3600s

options:
  env:
    - 'PROJECT=$PROJECT_ID'
    - 'IMAGES_VERSION=$_IMAGES_VERSION'
    - 'ARTIFACTS=/workspace/output'

############################################################################
# BUILD PACKER IMAGES
############################################################################

steps:

# packer_images.
- name: us-central1-docker.pkg.dev/mlab-sandbox/build-images/epoxy-images:1.2
  args: [
    '/workspace/builder.sh', 'packer_images'
  ]

