# Timeout for complete build. Default is 10m.
timeout: 10800s

# The default disk size is 100GB. However, the stage1 ISOs are pretty big these
# days. 400GB  should give us some breathing room.
options:
  diskSizeGb: 400
  env:
    - 'PROJECT=$PROJECT_ID'
    - 'ARTIFACTS=/workspace/output'

############################################################################
# BUILD ARTIFACTS
############################################################################

steps:
# stage1 minimal kernel & initram using stock ubuntu kernel.
- name: gcr.io/$PROJECT_ID/epoxy-images
  args: [
    '/workspace/builder.sh', 'stage1_minimal'
  ]

# Copy the admin kubeconfig into the workspace so that builder.sh can verify the
# cluster k8s version before building stage3 images.
- name: gcr.io/cloud-builders/gsutil
  args: [
    'cp',
    'gs://k8s-support-$PROJECT/admin.conf',
    '/workspace/admin.conf',
  ]

# stage3_ubuntu images.
- name: gcr.io/$PROJECT_ID/epoxy-images
  args: [
    '/workspace/builder.sh', 'stage3_ubuntu'
  ]

# stage3_update images.
- name: gcr.io/$PROJECT_ID/epoxy-images
  args: [
    '/workspace/builder.sh', 'stage3_update'
  ]

############################################################################
# DEPLOY ARTIFACTS
#
# Note: the artifacts built above need to be copied to specific locations in
# the target bucket. Currently, the cloudbuilder 'artifacts' directive does
# not support multiple target locations. So, the steps below are explicit.
############################################################################

# stage3_ubuntu.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r',
    '/workspace/output/stage1_kernel.vmlinuz',
    '/workspace/output/stage1_initramfs.cpio.gz',
    '/workspace/output/stage3_kernel_ubuntu.vmlinuz',
    '/workspace/output/stage3_initramfs_ubuntu.cpio.gz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_ubuntu/*.json',
    'gs://epoxy-$PROJECT_ID/stage3_ubuntu/'
  ]

# stage3_update.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r',
    '/workspace/output/stage1_kernel.vmlinuz',
    '/workspace/output/stage1_initramfs.cpio.gz',
    '/workspace/output/stage3_kernel_update.vmlinuz',
    '/workspace/output/stage3_initramfs_update.cpio.gz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_update/*.json',
    'gs://epoxy-$PROJECT_ID/stage3_update/'
  ]
