# Timeout for complete build. Default is 10m.
timeout: 10800s

options:
  env:
    - 'PROJECT=$PROJECT_ID'
    - 'IMAGES_VERSION=$_IMAGES_VERSION'
    - 'ARTIFACTS=/workspace/output'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_NUMBER}/secrets/platform-ssh-host-ca-private-key/versions/latest
    env: SSH_HOST_CA_KEY

############################################################################
# BUILD ARTIFACTS
############################################################################

steps:
# stage1 minimal kernel & initram using stock ubuntu kernel.
- name: us-central1-docker.pkg.dev/$PROJECT_ID/build-images/epoxy-images:1.2
  args: [
    '/workspace/builder.sh', 'stage1_minimal'
  ]

# stage3_ubuntu images.
- name: us-central1-docker.pkg.dev/$PROJECT_ID/build-images/epoxy-images:1.2
  entrypoint: /bin/bash
  args:
  - '-c'
  - '/workspace/builder.sh stage3_ubuntu'
  secretEnv:
  - SSH_HOST_CA_KEY

# stage3_update images.
- name: us-central1-docker.pkg.dev/$PROJECT_ID/build-images/epoxy-images:1.2
  args: [
    '/workspace/builder.sh', 'stage3_update'
  ]

############################################################################
# DEPLOY VERSIONED ARTIFACTS
#
# Note: the artifacts built above need to be copied to specific locations in
# the target bucket. Currently, the cloudbuilder 'artifacts' directive does
# not support multiple target locations. So, the steps below are explicit.
############################################################################

# stage3_ubuntu.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r',
    '/workspace/output/stage1_kernel.vmlinuz',
    '/workspace/output/stage1_initramfs.cpio.gz',
    '/workspace/output/stage3_kernel_ubuntu.vmlinuz',
    '/workspace/output/stage3_initramfs_ubuntu.cpio.gz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_ubuntu/*.json',
    'gs://epoxy-$PROJECT_ID/$_IMAGES_VERSION/stage3_ubuntu/'
  ]

# stage3_update.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r',
    '/workspace/output/stage1_kernel.vmlinuz',
    '/workspace/output/stage1_initramfs.cpio.gz',
    '/workspace/output/stage3_kernel_update.vmlinuz',
    '/workspace/output/stage3_initramfs_update.cpio.gz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_update/*.json',
    'gs://epoxy-$PROJECT_ID/$_IMAGES_VERSION/stage3_update/'
  ]

